---
title: "data_wrangling"
author: "Qiwei Lin"
date: "2024-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r}
library(tidyverse)
library(readxl)
library(censusapi)
library(janitor)
# use your own key below
Sys.setenv(CENSUS_KEY="dbe04b6900453a6f813d1136af7fc11f9357932c")
```

# Prepare County-Level Data

## Prepare the County-Level Migration Flow Data

```{r}
# Function to clean and extract data from each sheet
process_sheet <- function(sheet_name, file_path) {
  # Read the sheet and skip the first 2 rows to get actual data
  df <- read_excel(file_path, sheet = sheet_name, skip = 2)
  
  # Clean up column names
  colnames(df) <- c("state_code_a", "fips_county_a", "state_code_b", "fips_county_b", 
                    "state_name_a", "county_name_a", "state_name_b", "county_name_b", 
                    "flow_b_to_a_estimate", "flow_b_to_a_moe", "flow_a_to_b_estimate", 
                    "flow_a_to_b_moe", "net_migration_estimate", "net_migration_moe", 
                    "gross_migration_estimate", "gross_migration_moe")
  
  # Filter out rows with missing values in essential columns
  df <- df %>%
    filter(!is.na(fips_county_a) & !is.na(fips_county_b)) %>%
    select(state_code_a, state_name_a, county_name_a, fips_county_a,
           state_code_b, state_name_b, county_name_b, fips_county_b,
           flow_b_to_a_estimate, flow_a_to_b_estimate,
           net_migration_estimate, gross_migration_estimate)
  
  return(df)
}
```

```{r}
# Get the list of sheets (each representing a state)
file_path <- "../data/raw_migration_data/county-to-county-2016-2020-ins-outs-nets-gross.xlsx"
sheets <- excel_sheets(file_path)

# Apply the process_sheet function to each sheet and combine the results into one dataframe
migration_data <- map_dfr(sheets, ~process_sheet(.x, file_path))
```

```{r}
flow_data <- migration_data %>% 
  mutate(fips_orig = str_c(state_code_a, fips_county_a),
         fips_dest = str_c(state_code_b, fips_county_b)) %>% 
  select("fips_orig", "fips_dest", contains("flow")) %>% 
  select(-flow_b_to_a_estimate) %>% 
  rename(flow = flow_a_to_b_estimate) %>% 
  filter(flow >= 25, 
         !str_detect(fips_orig, "^072"),
         !str_detect(fips_dest, "^072")) # remove Puerto Rico	

write_csv(flow_data, "../data/output_data/county_flow.csv")
```


## Prepare County-Level Sociodemographic Data

```{r}
download_acs_data <- function(year=2016){
  # ACS variable name
  var_lst <- c(
    "B01001_001E", # total population
    "B19013_001E", # median annual household income
    "B23025_005E", # the number of the unemployed 
    "B23025_003E", # the population size of civilian labor force
    "B17017_002E", # the number of households under poverty line
    "B17017_001E", # the number of households
    "B03002_002E", # non-Hispanic total
    "B03002_003E", # non-Hispanic white
    "B03002_004E", # non-Hispanic black
    "B03002_005E", # non-Hispanic Amer Indian and Alaska Native
    "B03002_006E", # non-Hispanic Asian
    "B03002_007E", # non-Hispanic NHPI
    "B03002_012E", # Hispanic or Latino
    "B01001_020E", # varaibles for age > 65
    "B01001_021E",
    "B01001_022E",
    "B01001_023E",
    "B01001_024E",
    "B01001_025E",
    "B01001_044E",
    "B01001_045E",
    "B01001_046E",
    "B01001_047E",
    "B01001_048E",
    "B01001_049E"
  )
  
  county_demo <- 
    getCensus(
      name = "acs/acs5",
      vintage = year,
      region = paste0("county", ":*"),
      #regionin = paste0("state:",state),
      vars = var_lst
    ) %>% 
    mutate(GEOID = paste0(state, county)) %>% 
    census_processing()

  return(county_demo)
}


```


```{r}
# a helper function to post-process census data
census_processing <- function(df){
  # remove NA and recode variables
  df_processed <- df %>% 
    map_dfr(.x=., ~replace(.x, .x==-666666666, NA)) %>% 
    mutate(
      unemp = B23025_005E/B23025_003E,
      pov = B17017_002E/B17017_001E,
      raw_non_other = rowSums(across(B03002_003E:B03002_007E),
                              na.rm = TRUE),
      EP_white = (B03002_003E/B01001_001E),
      EP_black = (B03002_004E/B01001_001E),
      EP_aian = (B03002_005E/B01001_001E),
      EP_asian = (B03002_006E/B01001_001E),
      EP_nhpi = (B03002_007E/B01001_001E),
      EP_hispanic = (B03002_012E/B01001_001E),
      EP_other = (B03002_002E - raw_non_other)/B01001_001E,
      age_65 = rowSums(across(B01001_020E:B01001_049E),
                              na.rm = TRUE) / B01001_001E) %>% 
    rename(
      tot_pop = B01001_001E, 
      median_inc = B19013_001E
    ) %>% 
    select(GEOID, tot_pop, median_inc, unemp, pov, 
           contains("EP"), age_65)
  
  # calculate the diversity index
  df_processed <- df_processed %>% 
    mutate(
      diveristy_idx = 1 - 
        rowSums(across(starts_with("EP_"), ~ .x^2), 
                na.rm = TRUE)
    )

  return(df_processed)
}

download_housing <- function(year=2016){
  var_lst <- c(
    "S2503_C01_001E", # number of housing units
    "S2503_C01_028E", # num of units with certain housing burden
    "S2503_C01_032E",
    "S2503_C01_036E",
    "S2503_C01_040E"
  )
  
  county_housing <- 
    getCensus(
      name = "acs/acs5/subject",
      vintage = year,
      region = paste0("county", ":*"),
      #regionin = paste0("state:",state),
      vars = var_lst
    ) %>% 
    mutate(
      GEOID = paste0(state, county),
      hou_burd = rowSums(across(S2503_C01_028E:S2503_C01_040E),
                                na.rm=T) / S2503_C01_001E,
      hou_burd = ifelse(hou_burd > 1, 1, hou_burd)) %>%  
    select(GEOID, hou_burd)
  
  return(county_housing)
}
```


```{r}
county_demo <- download_acs_data()

county_housing <- download_housing()
```

```{r}
election_data <- read_csv("../data/election_data/countypres_2000-2020.csv")
```

```{r}
election_data_clean <- election_data %>% 
  filter(year == 2016, office == "US PRESIDENT",
         party == "DEMOCRAT") %>% 
  mutate(vote_share = candidatevotes/totalvotes,
         county_fips = str_pad(county_fips, width = 6, 
                               pad = "0")) %>% 
  select(county_fips, vote_share)
```

```{r}
load("../data/crime_data/37059-0001-Data.rda")
crime <- da37059.0001 %>%
  mutate(across(contains("FIPS"), str_pad, width = 3, 
                pad = "0")) %>% 
  mutate(GEOID = str_c(FIPS_ST, FIPS_CTY)) %>% 
  select(GEOID, GRNDTOT) 
```

## Merge all county-level information

```{r}
county_info <- county_demo %>% 
  select(GEOID, tot_pop:pov, age_65, diveristy_idx) %>% 
  left_join(county_housing, by="GEOID") %>% 
  mutate(GEOID = str_pad(GEOID, width = 6, pad = "0")) %>% 
  left_join(election_data_clean, by=c("GEOID"="county_fips")) %>% 
  left_join(crime, by="GEOID") %>% 
  filter(!str_detect(GEOID, "^072")) %>% 
  mutate(GRNDTOT = replace_na(GRNDTOT, 0),
         vote_share = case_when(
           is.na(vote_share) & str_detect(GEOID, "^002") ~ 0.3655, 
           is.na(vote_share) & str_detect(GEOID, "^015") ~ 0.7,
           T ~ vote_share
         ),
         crime_rate = GRNDTOT / tot_pop) %>% 
  select(-GRNDTOT) %>% 
  arrange(GEOID)
```

## Load Google Population Dynamics Foundation Model (PDFM) Embeddings

```{r}
pdfm <- read_csv("../data/PDFM_data/county_embeddings.csv") %>% 
  mutate(GEOID = str_extract(place, "[0-9]+") %>% 
           str_pad(width = 6, pad = "0")) %>% 
  select(GEOID, contains("feature"))
```
```{r}
flow_data_filterd <- flow_data %>% 
  inner_join(county_info %>% select(GEOID), 
             by=c("fips_orig"="GEOID")) %>% 
  inner_join(county_info %>% select(GEOID), 
             by=c("fips_dest"="GEOID"))

write_csv(flow_data_filterd, "../data/output_data/county_flow.csv")
```

```{r}
all_nodes <- c(
  flow_data_filterd$fips_orig, 
  flow_data_filterd$fips_dest
) %>% unique()

# for counties without PDFM embedding, we fill in with 
# all-one vectors

county_info %>% 
  filter(GEOID %in% all_nodes) %>%
  left_join(pdfm, by="GEOID") %>% 
  mutate(across(contains("feature"), ~replace_na(., 1))) %>% 
  write_csv("../data/output_data/county_node_info.csv")
```


# Prepare International Migration Data

## Prepare International flow data

```{r}
migration <- read_csv("../data/raw_migration_data/bilat_mig.csv")

int_migration <- migration %>% 
  filter(year0 == "2015", da_pb_closed > 100) %>% 
  select(orig, dest, da_pb_closed) %>% 
  rename(flow = da_pb_closed) 
```

## Prepare International Covariates

````{r}
# load world bank population data for merge
population <- read_csv("../data/population_data/world_bank_population_data.csv")

int_population <- population%>%
  clean_names()%>%
  select(c(country_name, country_code, x2015))%>%
  rename(population = x2015)

# load world bank age-dependency ratio data for merge
age_ratio <- read_csv("../data/population_data/age_dependency_ratio.csv")%>%
  clean_names()%>%
  select(c(country_code, year, value))%>%
  rename(age_ratio = value)%>%
  filter(year == 2015)

# load world bank per-capita gdp data for merge
gdp <- read_csv("../data/population_data/wb_per_capita_gdp.csv")%>%
  clean_names%>%
  select(c(country_code,x2015))%>%
  rename(per_capita_gdp = x2015)

# load world bank unemployment data for merge
unemployment <- read_csv("../data/population_data/wb_unemployment_data.csv")%>%
  clean_names%>%
  select(c(country_code,x2015))%>%
  rename(per_capita_gdp = x2015)

#load pre-prepared vdem data
#The high-level electoral democracy index only covers 179 countries
vdem_data <- read_csv("../data/population_data/vdem_short.csv")

#load and prepare World Trade Analysis Project Data
```
